name: SonarCloud

on:
    workflow_run:
        workflows:
            - PHPunit
        branches:
            - master
            - dev
        types:
            - completed

jobs:
    sonar_cloud:
        # `if` required because a workflow run is triggered regardless of
        # the result of the previous workflow (see the documentation page)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '8.0' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.event.workflow_run.head_branch }}

            -   name: Change paths in clover.xml
                run: |
                    sed -i 's+/home/runner/work/bundle-stripe/bundle-aws-ses-monitor+/github/workspace+g' ./var/coverage/clover.xml

            -   name: Sonarcloud
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
